default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stackoverflow_development
test:
  <<: *default
  database: stackoverflow_test

production:
  <<: *default
  database: stackoverflow_production
  username: stackoverflow
  password: <%= ENV['STACKOVERFLOW_DATABASE_PASSWORD'] %>
